name: Daily DevOps Job Alert

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs daily at 11:25 AM IST (5:55 AM UTC)
#   workflow_dispatch:

jobs:
  job_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: listing files
        run: ls -la

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run job alert script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python job_alert.py
